/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as HandoffsRouteImport } from './routes/handoffs'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FlowsRouteImport } from './routes/flows'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as CostsRouteImport } from './routes/costs'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as CapasRouteImport } from './routes/capas'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AppStoreRouteImport } from './routes/app-store'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersIndexRouteImport } from './routes/members.index'
import { Route as DepartmentsIndexRouteImport } from './routes/departments.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as MembersMemberIdRouteImport } from './routes/members.$memberId'
import { Route as DepartmentsIdRouteImport } from './routes/departments.$id'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as KnowledgeBasesKbIdContentRouteImport } from './routes/knowledge_.bases.$kbId.content'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffsRoute = HandoffsRouteImport.update({
  id: '/handoffs',
  path: '/handoffs',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsRoute = CostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const CapasRoute = CapasRouteImport.update({
  id: '/capas',
  path: '/capas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStoreRoute = AppStoreRouteImport.update({
  id: '/app-store',
  path: '/app-store',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembersRoute,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DepartmentsRoute,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/$memberId',
  path: '/$memberId',
  getParentRoute: () => MembersRoute,
} as any)
const DepartmentsIdRoute = DepartmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DepartmentsRoute,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const KnowledgeBasesKbIdContentRoute =
  KnowledgeBasesKbIdContentRouteImport.update({
    id: '/knowledge_/bases/$kbId/content',
    path: '/knowledge/bases/$kbId/content',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agents': typeof AgentsRouteWithChildren
  '/app-store': typeof AppStoreRoute
  '/audit': typeof AuditRoute
  '/capas': typeof CapasRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/copilot': typeof CopilotRoute
  '/costs': typeof CostsRoute
  '/credentials': typeof CredentialsRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/flows': typeof FlowsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/governance': typeof GovernanceRoute
  '/handoffs': typeof HandoffsRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/models': typeof ModelsRoute
  '/plugins': typeof PluginsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/statistics': typeof StatisticsRoute
  '/welcome': typeof WelcomeRoute
  '/workspace': typeof WorkspaceRoute
  '/agents/$id': typeof AgentsIdRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/knowledge/bases/$kbId/content': typeof KnowledgeBasesKbIdContentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/app-store': typeof AppStoreRoute
  '/audit': typeof AuditRoute
  '/capas': typeof CapasRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/copilot': typeof CopilotRoute
  '/costs': typeof CostsRoute
  '/credentials': typeof CredentialsRoute
  '/flows': typeof FlowsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/governance': typeof GovernanceRoute
  '/handoffs': typeof HandoffsRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/plugins': typeof PluginsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/statistics': typeof StatisticsRoute
  '/welcome': typeof WelcomeRoute
  '/workspace': typeof WorkspaceRoute
  '/agents/$id': typeof AgentsIdRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/agents': typeof AgentsIndexRoute
  '/departments': typeof DepartmentsIndexRoute
  '/members': typeof MembersIndexRoute
  '/knowledge/bases/$kbId/content': typeof KnowledgeBasesKbIdContentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agents': typeof AgentsRouteWithChildren
  '/app-store': typeof AppStoreRoute
  '/audit': typeof AuditRoute
  '/capas': typeof CapasRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/copilot': typeof CopilotRoute
  '/costs': typeof CostsRoute
  '/credentials': typeof CredentialsRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/flows': typeof FlowsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/governance': typeof GovernanceRoute
  '/handoffs': typeof HandoffsRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/models': typeof ModelsRoute
  '/plugins': typeof PluginsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/statistics': typeof StatisticsRoute
  '/welcome': typeof WelcomeRoute
  '/workspace': typeof WorkspaceRoute
  '/agents/$id': typeof AgentsIdRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/knowledge_/bases/$kbId/content': typeof KnowledgeBasesKbIdContentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/agents'
    | '/app-store'
    | '/audit'
    | '/capas'
    | '/confirm-email'
    | '/copilot'
    | '/costs'
    | '/credentials'
    | '/departments'
    | '/flows'
    | '/forgot-password'
    | '/governance'
    | '/handoffs'
    | '/integrations'
    | '/knowledge'
    | '/login'
    | '/members'
    | '/models'
    | '/plugins'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/skills'
    | '/statistics'
    | '/welcome'
    | '/workspace'
    | '/agents/$id'
    | '/departments/$id'
    | '/members/$memberId'
    | '/agents/'
    | '/departments/'
    | '/members/'
    | '/knowledge/bases/$kbId/content'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/app-store'
    | '/audit'
    | '/capas'
    | '/confirm-email'
    | '/copilot'
    | '/costs'
    | '/credentials'
    | '/flows'
    | '/forgot-password'
    | '/governance'
    | '/handoffs'
    | '/integrations'
    | '/knowledge'
    | '/login'
    | '/models'
    | '/plugins'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/skills'
    | '/statistics'
    | '/welcome'
    | '/workspace'
    | '/agents/$id'
    | '/departments/$id'
    | '/members/$memberId'
    | '/agents'
    | '/departments'
    | '/members'
    | '/knowledge/bases/$kbId/content'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/agents'
    | '/app-store'
    | '/audit'
    | '/capas'
    | '/confirm-email'
    | '/copilot'
    | '/costs'
    | '/credentials'
    | '/departments'
    | '/flows'
    | '/forgot-password'
    | '/governance'
    | '/handoffs'
    | '/integrations'
    | '/knowledge'
    | '/login'
    | '/members'
    | '/models'
    | '/plugins'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/skills'
    | '/statistics'
    | '/welcome'
    | '/workspace'
    | '/agents/$id'
    | '/departments/$id'
    | '/members/$memberId'
    | '/agents/'
    | '/departments/'
    | '/members/'
    | '/knowledge_/bases/$kbId/content'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  AppStoreRoute: typeof AppStoreRoute
  AuditRoute: typeof AuditRoute
  CapasRoute: typeof CapasRoute
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  CopilotRoute: typeof CopilotRoute
  CostsRoute: typeof CostsRoute
  CredentialsRoute: typeof CredentialsRoute
  DepartmentsRoute: typeof DepartmentsRouteWithChildren
  FlowsRoute: typeof FlowsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GovernanceRoute: typeof GovernanceRoute
  HandoffsRoute: typeof HandoffsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRouteWithChildren
  ModelsRoute: typeof ModelsRoute
  PluginsRoute: typeof PluginsRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  StatisticsRoute: typeof StatisticsRoute
  WelcomeRoute: typeof WelcomeRoute
  WorkspaceRoute: typeof WorkspaceRoute
  KnowledgeBasesKbIdContentRoute: typeof KnowledgeBasesKbIdContentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoffs': {
      id: '/handoffs'
      path: '/handoffs'
      fullPath: '/handoffs'
      preLoaderRoute: typeof HandoffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs': {
      id: '/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof CostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capas': {
      id: '/capas'
      path: '/capas'
      fullPath: '/capas'
      preLoaderRoute: typeof CapasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-store': {
      id: '/app-store'
      path: '/app-store'
      fullPath: '/app-store'
      preLoaderRoute: typeof AppStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof MembersRoute
    }
    '/departments/': {
      id: '/departments/'
      path: '/'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof DepartmentsRoute
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/members/$memberId': {
      id: '/members/$memberId'
      path: '/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof MembersRoute
    }
    '/departments/$id': {
      id: '/departments/$id'
      path: '/$id'
      fullPath: '/departments/$id'
      preLoaderRoute: typeof DepartmentsIdRouteImport
      parentRoute: typeof DepartmentsRoute
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/knowledge_/bases/$kbId/content': {
      id: '/knowledge_/bases/$kbId/content'
      path: '/knowledge/bases/$kbId/content'
      fullPath: '/knowledge/bases/$kbId/content'
      preLoaderRoute: typeof KnowledgeBasesKbIdContentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface DepartmentsRouteChildren {
  DepartmentsIdRoute: typeof DepartmentsIdRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
}

const DepartmentsRouteChildren: DepartmentsRouteChildren = {
  DepartmentsIdRoute: DepartmentsIdRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
}

const DepartmentsRouteWithChildren = DepartmentsRoute._addFileChildren(
  DepartmentsRouteChildren,
)

interface MembersRouteChildren {
  MembersMemberIdRoute: typeof MembersMemberIdRoute
  MembersIndexRoute: typeof MembersIndexRoute
}

const MembersRouteChildren: MembersRouteChildren = {
  MembersMemberIdRoute: MembersMemberIdRoute,
  MembersIndexRoute: MembersIndexRoute,
}

const MembersRouteWithChildren =
  MembersRoute._addFileChildren(MembersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AgentsRoute: AgentsRouteWithChildren,
  AppStoreRoute: AppStoreRoute,
  AuditRoute: AuditRoute,
  CapasRoute: CapasRoute,
  ConfirmEmailRoute: ConfirmEmailRoute,
  CopilotRoute: CopilotRoute,
  CostsRoute: CostsRoute,
  CredentialsRoute: CredentialsRoute,
  DepartmentsRoute: DepartmentsRouteWithChildren,
  FlowsRoute: FlowsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GovernanceRoute: GovernanceRoute,
  HandoffsRoute: HandoffsRoute,
  IntegrationsRoute: IntegrationsRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRouteWithChildren,
  ModelsRoute: ModelsRoute,
  PluginsRoute: PluginsRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  StatisticsRoute: StatisticsRoute,
  WelcomeRoute: WelcomeRoute,
  WorkspaceRoute: WorkspaceRoute,
  KnowledgeBasesKbIdContentRoute: KnowledgeBasesKbIdContentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
